### ISSUE TITLE
Pass for prioritise_transaction.py

### ISSUE THREAD

**Issue by shohu** [shohu/c0ban#38]
```
# test/functional/prioritise_transaction.py
2018-05-31 06:55:37.447000 TestFramework (INFO): Initializing test directory /tmp/testhqwwjm3p
2018-05-31 06:55:40.779000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/c0ban/test/functional/test_framework/test_framework.py", line 120, in main
    self.run_test()
  File "test/functional/prioritise_transaction.py", line 43, in run_test
    assert(sizes[i] > MAX_BLOCK_BASE_SIZE) # Fail => raise utxo_count
AssertionError
2018-05-31 06:55:40.786000 TestFramework (INFO): Stopping nodes
2018-05-31 06:55:42.964000 TestFramework (WARNING): Not cleaning up dir /tmp/testhqwwjm3p
2018-05-31 06:55:42.964000 TestFramework (ERROR): Test failed. Test logging available at /tmp/testhqwwjm3p/test_framework.log
```

**Comment by shohu** [comment]
Try following parameter.
```
        // nSwitchLyra2REv2_DIFF = 200;
        nSwitchLyra2REv2_DIFF = 100000000;
```
But I got same error.

**Comment by shohu** [comment]
I tried to do test by "before modification c0ban source". I got same error.
So This error is original bug
