### ISSUE TITLE
Pass for signmessages.py

### ISSUE THREAD

**Issue by shohu** [shohu/c0ban#41]
test code 
```
# test/functional/signmessages.py
2018-06-01 09:19:46.236000 TestFramework (INFO): Initializing test directory /tmp/testm6k4ia30
2018-06-01 09:19:46.503000 TestFramework (INFO): test signing with priv_key
2018-06-01 09:19:46.505000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/c0ban/test/functional/test_framework/test_framework.py", line 120, in main
    self.run_test()
  File "test/functional/signmessages.py", line 23, in run_test
    assert_equal(expected_signature, signature)
  File "/c0ban/test/functional/test_framework/util.py", line 38, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(INbVnW4e6PeRmsv2Qgu8NuopvrVjkcxob+sX8OcZG0SALhWybUjzMLPdAsXI46YZGb0KQTRii+wWIQzRpG/U+S0= == H5JqAg5b5Yb9COhYARHKht5uj0Bl9lQ5YLqwWyVU0/V7SEVJTk3LmoPoRExqpxPjuHVMQd7oV7KwZoF4L+FlFAw=)
2018-06-01 09:19:46.520000 TestFramework (INFO): Stopping nodes
2018-06-01 09:19:48.658000 TestFramework (WARNING): Not cleaning up dir /tmp/testm6k4ia30
2018-06-01 09:19:48.658000 TestFramework (ERROR): Test failed. Test logging available at /tmp/testm6k4ia30/test_framework.log
```
debug.log
```
Maybe not related
```

**Comment by shohu** [comment]
I don't think that this error was occured by hardfork modification.
Because this test is "messages sign test".

So I will try to test by before hardfork source.

**Comment by shohu** [comment]
I found error cause.
I changed following source.

![2018-06-06 13 23 38](https://user-images.githubusercontent.com/1214532/41016828-d87754f8-698c-11e8-9c39-7d8c5c84d9de.jpg)
