### ISSUE TITLE
Pass for assumevalid.py

### ISSUE THREAD

**Issue by shohu** [shohu/c0ban#44]
test code output
```
# test/functional/assumevalid.py
2018-06-01 09:57:14.746000 TestFramework (INFO): Initializing test directory /tmp/test4tew0cb6
2018-06-01 09:57:15.010000 TestFramework.mininode (INFO): Connecting to Bitcoin Node: 127.0.0.1:14518
2018-06-01 09:57:15.571000 TestFramework.mininode (INFO): Connecting to Bitcoin Node: 127.0.0.1:14519
2018-06-01 09:57:15.937000 TestFramework.mininode (INFO): Connecting to Bitcoin Node: 127.0.0.1:14520

2018-06-01 09:58:15.977000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/c0ban/test/functional/test_framework/test_framework.py", line 120, in main
    self.run_test()
  File "test/functional/assumevalid.py", line 179, in run_test
    node2.wait_for_verack()
  File "/c0ban/test/functional/test_framework/mininode.py", line 1605, in wait_for_verack
    wait_until(test_function, timeout=timeout, lock=mininode_lock)
  File "/c0ban/test/functional/test_framework/util.py", line 222, in wait_until
    assert_greater_than(timeout, time.time())
  File "/c0ban/test/functional/test_framework/util.py", line 42, in assert_greater_than
    raise AssertionError("%s <= %s" % (str(thing1), str(thing2)))
AssertionError: 1527847095.9402797 <= 1527847095.977221
2018-06-01 09:58:16.004000 TestFramework (INFO): Stopping nodes
2018-06-01 09:58:18.240000 TestFramework (WARNING): Not cleaning up dir /tmp/test4tew0cb6
2018-06-01 09:58:18.240000 TestFramework (ERROR): Test failed. Test logging available at /tmp/test4tew0cb6/test_framework.log
```
debug.log
```
Maybe not related
```

**Comment by shohu** [comment]
I changed to #35 source.
I got success.
```
# test/functional/assumevalid.py
2018-06-05 07:20:23.947000 TestFramework (INFO): Initializing test directory /tmp/testrp4cwbxu
2018-06-05 07:20:24.212000 TestFramework.mininode (INFO): Connecting to Bitcoin Node: 127.0.0.1:11139
2018-06-05 07:20:24.861000 TestFramework.mininode (INFO): Connecting to Bitcoin Node: 127.0.0.1:11140
2018-06-05 07:20:25.225000 TestFramework.mininode (INFO): Connecting to Bitcoin Node: 127.0.0.1:11141
2018-06-05 07:20:33.421000 TestFramework (INFO): Stopping nodes
2018-06-05 07:20:35.626000 TestFramework (INFO): Cleaning up
2018-06-05 07:20:35.631000 TestFramework (INFO): Tests successful
```
