### ISSUE TITLE
Pass signlogic for blockchain.py

### ISSUE THREAD

**Issue by shohu** [shohu/c0ban#58]
```
# test/functional/decodescript.py
2018-07-11 05:35:35.386000 TestFramework (INFO): Initializing test directory /tmp/test_mubbl_a
2018-07-11 05:35:35.675000 TestFramework (INFO): Stopping nodes
2018-07-11 05:35:37.810000 TestFramework (INFO): Cleaning up
2018-07-11 05:35:37.811000 TestFramework (INFO): Tests successful
root@4ba0752dae6b:/c0ban# test/functional/blockchain.py
2018-07-11 05:35:47.675000 TestFramework (INFO): Initializing test directory /tmp/test17gkuq23
2018-07-11 05:35:48.122000 TestFramework (INFO): Test that gettxoutsetinfo() works for blockchain with just the genesis block
2018-07-11 05:35:48.161000 TestFramework (INFO): Test that gettxoutsetinfo() returns the same result after invalidate/reconsider block
2018-07-11 05:35:48.288000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/c0ban/test/functional/test_framework/test_framework.py", line 120, in main
    self.run_test()
  File "test/functional/blockchain.py", line 41, in run_test
    self._test_getblockheader()
  File "test/functional/blockchain.py", line 120, in _test_getblockheader
    assert isinstance(header['difficulty'], Decimal)
AssertionError
2018-07-11 05:35:48.295000 TestFramework (INFO): Stopping nodes
2018-07-11 05:35:50.455000 TestFramework (WARNING): Not cleaning up dir /tmp/test17gkuq23
2018-07-11 05:35:50.455000 TestFramework (ERROR): Test failed. Test logging available at /tmp/test17gkuq23/test_framework.log
```

**Comment by shohu** [comment]
```
# test/functional/decodescript.py
2018-07-12 06:17:11.140000 TestFramework (INFO): Initializing test directory /tmp/testv46v70x3
2018-07-12 06:17:11.430000 TestFramework (INFO): Stopping nodes
2018-07-12 06:17:13.554000 TestFramework (INFO): Cleaning up
2018-07-12 06:17:13.558000 TestFramework (INFO): Tests successful
```
