### ISSUE TITLE
Pass signlogic for prioritise_transaction.py

### ISSUE THREAD

**Issue by shohu** [shohu/c0ban#59]
```
# test/functional/prioritise_transaction.py
2018-07-11 05:51:34.991000 TestFramework (INFO): Initializing test directory /tmp/testkaso102b
2018-07-11 05:51:36.753000 TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/c0ban/test/functional/test_framework/test_framework.py", line 120, in main
    self.run_test()
  File "test/functional/prioritise_transaction.py", line 32, in run_test
    txids[i] = create_lots_of_big_transactions(self.nodes[0], self.txouts, utxos[start_range:end_range], end_range - start_range, (i+1)*base_fee)
  File "/c0ban/test/functional/test_framework/util.py", line 553, in create_lots_of_big_transactions
    signresult = node.signrawtransaction(newtx, None, None, "NONE")
  File "/c0ban/test/functional/test_framework/coverage.py", line 46, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/c0ban/test/functional/test_framework/authproxy.py", line 154, in __call__
    raise JSONRPCException(response['error'])
test_framework.authproxy.JSONRPCException: Signature must use SIGHASH_FORKID (-8)
2018-07-11 05:51:36.770000 TestFramework (INFO): Stopping nodes
2018-07-11 05:51:39.015000 TestFramework (WARNING): Not cleaning up dir /tmp/testkaso102b
2018-07-11 05:51:39.015000 TestFramework (ERROR): Test failed. Test logging available at /tmp/testkaso102b/test_framework.log
```

**Comment by shohu** [comment]
I passed this test by https://github.com/shohu/c0ban/commit/95f42812d6b56f4aa37daad5fee8fc1e3eaf98bd 👍 
```
# test/functional/prioritise_transaction.py
2018-07-12 04:33:39.980000 TestFramework (INFO): Initializing test directory /tmp/testy8ehboyu
2018-07-12 04:33:52.551000 TestFramework (INFO): Assert that prioritised transaction was mined
2018-07-12 04:33:53.560000 TestFramework (INFO): Assert that de-prioritised transaction is still in mempool
2018-07-12 04:33:53.656000 TestFramework (INFO): Assert that prioritised free transaction is accepted to mempool
2018-07-12 04:33:54.471000 TestFramework (INFO): Stopping nodes
2018-07-12 04:33:56.940000 TestFramework (INFO): Cleaning up
2018-07-12 04:33:56.963000 TestFramework (INFO): Tests successful
```
