### ISSUE TITLE
Pass signlogic for mining.py

### ISSUE THREAD

**Issue by shohu** [shohu/c0ban#60]
```
# test/functional/mining.py
2018-07-11 05:55:03.041000 TestFramework (INFO): Initializing test directory /tmp/testvt5hlngh
2018-07-11 05:55:03.821000 TestFramework (INFO): getmininginfo
2018-07-11 05:55:03.822000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/c0ban/test/functional/test_framework/test_framework.py", line 120, in main
    self.run_test()
  File "test/functional/mining.py", line 43, in run_test
    assert_equal(mining_info['difficulty'], Decimal('4.656542373906925E-10'))
  File "/c0ban/test/functional/test_framework/util.py", line 38, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(1 == 4.656542373906925E-10)
2018-07-11 05:55:03.838000 TestFramework (INFO): Stopping nodes
2018-07-11 05:55:06.044000 TestFramework (WARNING): Not cleaning up dir /tmp/testvt5hlngh
2018-07-11 05:55:06.044000 TestFramework (ERROR): Test failed. Test logging available at /tmp/testvt5hlngh/test_framework.log
```

**Comment by shohu** [comment]
I passed this test 👍 
```
# test/functional/mining.py
2018-07-12 06:20:51.243000 TestFramework (INFO): Initializing test directory /tmp/testhnie9juo
2018-07-12 06:20:51.966000 TestFramework (INFO): getmininginfo
2018-07-12 06:20:51.980000 TestFramework (INFO): getblocktemplate: Test capability advertised
2018-07-12 06:20:51.981000 TestFramework (INFO): getblocktemplate: Test valid block
2018-07-12 06:20:51.983000 TestFramework (INFO): submitblock: Test block decode failure
2018-07-12 06:20:51.985000 TestFramework (INFO): getblocktemplate: Test bad input hash for coinbase transaction
2018-07-12 06:20:51.987000 TestFramework (INFO): submitblock: Test invalid coinbase transaction
2018-07-12 06:20:51.988000 TestFramework (INFO): getblocktemplate: Test truncated final transaction
2018-07-12 06:20:51.990000 TestFramework (INFO): getblocktemplate: Test duplicate transaction
2018-07-12 06:20:51.992000 TestFramework (INFO): getblocktemplate: Test invalid transaction
2018-07-12 06:20:51.995000 TestFramework (INFO): getblocktemplate: Test nonfinal transaction
2018-07-12 06:20:51.997000 TestFramework (INFO): getblocktemplate: Test bad tx count
2018-07-12 06:20:51.998000 TestFramework (INFO): getblocktemplate: Test bad bits
2018-07-12 06:20:52.001000 TestFramework (INFO): getblocktemplate: Test bad merkle root
2018-07-12 06:20:52.003000 TestFramework (INFO): getblocktemplate: Test bad timestamps
2018-07-12 06:20:52.006000 TestFramework (INFO): getblocktemplate: Test not best block
2018-07-12 06:20:52.007000 TestFramework (INFO): Stopping nodes
2018-07-12 06:20:54.122000 TestFramework (INFO): Cleaning up
2018-07-12 06:20:54.133000 TestFramework (INFO): Tests successful
```
