### ISSUE TITLE
Pass signlogic for txn_clone.py

### ISSUE THREAD

**Issue by shohu** [shohu/c0ban#65]
```
# test/functional/txn_clone.py
2018-07-11 06:36:50.641000 TestFramework (INFO): Initializing test directory /tmp/test48wedktw
2018-07-11 06:36:52.496000 TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/c0ban/test/functional/test_framework/test_framework.py", line 120, in main
    self.run_test()
  File "test/functional/txn_clone.py", line 74, in run_test
    tx1_clone = self.nodes[0].signrawtransaction(clone_raw, None, None, "ALL|ANYONECANPAY")
  File "/c0ban/test/functional/test_framework/coverage.py", line 46, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/c0ban/test/functional/test_framework/authproxy.py", line 154, in __call__
    raise JSONRPCException(response['error'])
test_framework.authproxy.JSONRPCException: Signature must use SIGHASH_FORKID (-8)
2018-07-11 06:36:52.508000 TestFramework (INFO): Stopping nodes
2018-07-11 06:36:54.774000 TestFramework (WARNING): Not cleaning up dir /tmp/test48wedktw
2018-07-11 06:36:54.775000 TestFramework (ERROR): Test failed. Test logging available at /tmp/test48wedktw/test_framework.log
```

**Comment by shohu** [comment]
I passed this test 👍 
```
# test/functional/txn_clone.py
2018-07-12 04:43:44.134000 TestFramework (INFO): Initializing test directory /tmp/test8kwj551m
2018-07-12 04:43:46.420000 TestFramework (INFO): Stopping nodes
2018-07-12 04:43:48.652000 TestFramework (INFO): Cleaning up
2018-07-12 04:43:48.673000 TestFramework (INFO): Tests successful
```
