### ISSUE TITLE
Create windows binary

### ISSUE THREAD

**Issue by shohu** [shohu/c0ban#69]
I tried to create windows binary when I got error.
```
# make deploy
Making all in src
make[1]: Entering directory `/c0ban/src'
make[2]: Entering directory `/c0ban/src'
make[2]: Leaving directory `/c0ban/src'
make[1]: Leaving directory `/c0ban/src'
Making all in doc/man
make[1]: Entering directory `/c0ban/doc/man'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/c0ban/doc/man'
make[1]: Entering directory `/c0ban'
make[1]: Nothing to be done for `all-am'.
make[1]: Leaving directory `/c0ban'
/bin/mkdir -p ./release
STRIPPROG="/usr/bin/x86_64-w64-mingw32-strip" /bin/bash /c0ban/build-aux/install-sh -c -s ./src/c0band.exe ./release
STRIPPROG="/usr/bin/x86_64-w64-mingw32-strip" /bin/bash /c0ban/build-aux/install-sh -c -s ./src/qt/c0ban-qt.exe ./release
STRIPPROG="/usr/bin/x86_64-w64-mingw32-strip" /bin/bash /c0ban/build-aux/install-sh -c -s ./src/c0ban-cli.exe ./release
error: could not build c0ban-0.15.1-win64-setup.exe
built c0ban-0.15.1-win64-setup.exe
```

**Comment by shohu** [comment]
I found error of cause !
https://github.com/bitcoin/bitcoin/issues/12876.

I will try to following command.
```
sudo apt install nsis
makensis share/setup.nsi
```

But I got following .
```
# npm install -g makensis
npm http GET https://registry.npmjs.org/makensis
npm http GET https://registry.npmjs.org/makensis

npm http GET https://registry.npmjs.org/makensis
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
```
But I got setup.exe after following command 👍
``` 
apt-get install -y npm
npm install -g makensis
npm config set strict-ssl false
npm install -g makensis
makensis share/setup.nsi
```
